### ISSUE TITLE
st7789py.py: WIDTH_320 Rotation Table Values Reversed

### ISSUE THREAD

**Issue by connorhickton** [russhughes/st7789py_mpy#1]
Apologies if this is done improperly, I am _very_ new to GitHub.

In lib/st7789py.py, it looks like the values for the rotation table WIDTH_320 are reversed (240 should be 320 and vice versa). I was encountering errors with my 320x240 display not showing the full screen beyond 240x240, until I swapped all the values. The swapped values also better reflects the pattern from WIDTH_135.

I've attached images to show the issue:

Old Rotation Table WIDTH_320 is:
```
WIDTH_320 = [(320, 240,  0,  0),
             (240, 320,  0,  0),
             (320, 240,  0,  0),
             (240, 320,  0,  0)]
```
![20211222_222944](https://user-images.githubusercontent.com/82282440/147199129-e0adf30e-faf6-4ea3-b7b4-d5f38f1dd159.jpg)

Fixed Rotation Table WIDTH_320 is:
```
WIDTH_320 = [(240, 320,  0,  0),
             (320, 240,  0,  0),
             (240, 320,  0,  0),
             (320, 240,  0,  0)]
```
![20211222_222840](https://user-images.githubusercontent.com/82282440/147199136-4fdd505a-d572-414d-bcf4-7242beafe919.jpg)

Thanks for the code otherwise - this is my first time controlling a display with a microcontroller, and I wouldn't have been able to do it without this code!

**Comment by russhughes** [comment]
You are correct; I had the widths and heights reversed in the WIDTH_320 table. Thanks for the report.
