### ISSUE TITLE
ESP or RP2040?

### ISSUE THREAD

**Issue by slabua** [russhughes/st7789py_mpy#2]
Is this driver for the ESP or the RP2040 version?
Doesn't seem to work on the RP board.

**Comment by russhughes** [comment]
The driver will work on an RP2040. However, I've run into issues with hardware SPI and non-standard pin use with some displays. In addition, the stock MicroPython 1.17 I've been using has issues with MISO=None. SoftSPI works but is slower. I've added examples for Waveshare Pico-LCD-1.14 and Pico-LCD-1.3 displays using SoftSPI.

**Comment by slabua** [comment]
Hm, that's strange then. I tried it on a LILYGO TTGO T-Display RP2040, there is no error but also nothing shows up in the display, so I thought the pins were wrongly assigned by default, but then again probably it would has spit some kind of error.

**Comment by slabua** [comment]
@russhughes the pins for the RP version are different https://github.com/Xinyuan-LilyGO/LILYGO-T-display-RP2040#product-
despite changing them in your examples, still no luck for me.

**Comment by russhughes** [comment]
What does your st7789 init code look like?  Are you using SPI or SoftSPI?

I have a T-Display RP2040 in transit somewhere between ShaTian and the USA, scheduled to arrive around January 24 - February 14.  Once it comes, I'll check it out.

**Comment by slabua** [comment]
@russhughes Hi I fixed it with the following settings.
The display needs to be explicitly powered on with the first 2 lines and the pins are as follows.
One thing though, miso pin is supposed to be left unused. I had to forcibly use some other pin, I didn't pick yet into the lib itself to check whether it can be skipped.

(Meanwhile today I received also the ESP version of the board and the driver works good with that.)

```
    p22 = Pin(22, Pin.OUT)
    p22.value(1)

    spi = SoftSPI(
        baudrate=20000000,
        polarity=1,
        phase=0,
        sck=Pin(2),
        mosi=Pin(3),
        miso=Pin(13))

    tft = st7789.ST7789(
        spi,
        135,
        240,
        reset=Pin(0, Pin.OUT),
        cs=Pin(5, Pin.OUT),
        dc=Pin(1, Pin.OUT),
        backlight=Pin(4, Pin.OUT),
        rotation=1)
```

**Comment by Gruftgrabbler** [comment]
Honestly I wasn't able to use Hardware SPI even on an esp32 module and SoftSPI is way to slow for the application I need

**Comment by chrisbanda72** [comment]
> @russhughes Hi I fixed it with the following settings. The display needs to be explicitly powered on with the first line and the pins are as follows. One thing though, miso pin is supposed to be left unused. I had to forcibly use some other pin, I didn't pick yet into the lib itself to check whether it can be skipped.
> 
> (Meanwhile today I received also the ESP version of the board and the driver works good with that.)
> 
> Btw, SPI doesn't seem to work. Specifying id=0 gives no results, id=1 complains about the wrong sck pin.
> 
> ```
>     Pin(22, Pin.OUT, value=1)
> 
>     spi = SoftSPI(
>         baudrate=20000000,
>         polarity=1,
>         phase=0,
>         sck=Pin(2),
>         mosi=Pin(3),
>         miso=Pin(13))
> 
>     tft = st7789.ST7789(
>         spi,
>         135,
>         240,
>         reset=Pin(0, Pin.OUT),
>         cs=Pin(5, Pin.OUT),
>         dc=Pin(1, Pin.OUT),
>         backlight=Pin(4, Pin.OUT),
>         rotation=1)
> ```

**Comment by chrisbanda72** [comment]
Slabua:  My name is Chris.  I'm having some issues with the WaveShare 1.14 using MirroPython on a RP 2040.  Could you or anyone who knows how to use this Waveshare 1.14 display, please call me at 323-218-1435.  I'm desperate for some help.  Thanks.
