### ISSUE TITLE
Loading Bitmaps on Raspberry Pico

### ISSUE THREAD

**Issue by fabulou1** [russhughes/st7789py_mpy#4]
Hi, 
thank you very much for the great library. I don't know if my issue is library specific or a general problem but i am trying to load a bitmap i created with the python code from the utils folder as a background. This causes a memory allocation error. I assume that the 256 kb is not enough. Is there a way to load from flash withouth filling up the ram? 

Best regards!

**Comment by russhughes** [comment]
They could be compiled into the MicroPython firmware as frozen byte code and accessed using a memoryview. Using a memoryview takes much less ram and is how I store the fonts for the 'C' version of the driver. See https://github.com/russhughes/st7789_mpy/blob/master/fonts/bitmap/vga1_8x8.py and https://github.com/peterhinch/micropython_data_to_py for examples. However, using memoryviews is more complicated as you have to recompile the MicroPython firmware to make changes. 

Another option would be to store the bitmap as a file in the device's filesystem, then read and copy it to the display in smaller chunks that fit in memory.
